export const mockProjects = [
  {
    id: 1,
    name: "WorkSync Dashboard",
    description: "Team collaboration tool with Kanban board and real-time chat",
    status: "active",
    members: 5,
    createdAt: "2026-01-15",
  },
  {
    id: 2,
    name: "Mobile App Redesign",
    description: "Redesigning the mobile app UI for better user experience",
    status: "active",
    members: 3,
    createdAt: "2026-02-10",
  },
  {
    id: 3,
    name: "API Migration",
    description: "Migrating REST APIs to GraphQL for better performance",
    status: "on-hold",
    members: 4,
    createdAt: "2026-03-01",
  },
  {
    id: 4,
    name: "Landing Page",
    description: "New marketing landing page with animations and dark mode",
    status: "completed",
    members: 2,
    createdAt: "2025-12-20",
  },
];

export const mockTasks = [
  {
    id: 1,
    title: "Design login page",
    description: "Create a clean login UI with email and password fields",
    status: "done",
    priority: "high",
    projectId: 1,
  },
  {
    id: 2,
    title: "Setup React Router",
    description: "Configure routes for all pages including protected routes",
    status: "done",
    priority: "high",
    projectId: 1,
  },
  {
    id: 3,
    title: "Build Kanban board",
    description: "Implement drag and drop task management board",
    status: "inprogress",
    priority: "high",
    projectId: 1,
  },
  {
    id: 4,
    title: "Redesign mobile navigation",
    description: "Improve bottom navigation bar for better UX",
    status: "inprogress",
    priority: "medium",
    projectId: 2,
  },
  {
    id: 5,
    title: "Write API documentation",
    description: "Document all GraphQL queries and mutations",
    status: "todo",
    priority: "medium",
    projectId: 3,
  },
  {
    id: 6,
    title: "Add dark mode support",
    description: "Implement dark mode toggle with localStorage persistence",
    status: "todo",
    priority: "low",
    projectId: 4,
  },
  {
    id: 7,
    title: "Setup analytics dashboard",
    description: "Integrate charts to display project and task statistics",
    status: "todo",
    priority: "medium",
    projectId: 1,
  },
  {
    id: 8,
    title: "Fix mobile responsiveness",
    description: "Make sidebar collapsible and layout responsive on small screens",
    status: "inprogress",
    priority: "high",
    projectId: 2,
  },
];